### PR TITLE
DropdownMenu: push invocation of props.close() to the call queue

### LINKED ISSUE #50: onClick event not triggered
Hi,

I try to use an onClick event for the menu items in my menu, but none of these events ever get fired (`console.log('You clicked an item');`)

I tried the exact same code from the example at https://github.com/mlaursen/react-dd-menu but without luck. Any idea why these events are not triggered? Thanks in advance!

### PR DESCRIPTION
**Pull request by williamboman**
This is to ensure that eventual event handlers consumers have regsitered via
React props are invoked first.

Closes #50. (I think)

### CODE REVIEW

**Comment by williamboman** [comment]
@mlaursen This is currently blocking a feature on one of our applications, would be awesome 🎉  if you could review + hopefully merge and release new patch version asap.

**Comment by williamboman** [comment]
The issue we're seeing is that the `props.close` callback is invoked before the `onClick` handler on the menu item that was clicked. The `props.close` callback will immediately change parent state to close the dropdown, and consequently React will unregister the `onClick` handler on the menu item before it's invoked, because it's being unmounted. I'm assuming this is what's happening, I tried to repro on Codepen but failed, I guess the repro code is too trivial and executes fast enough.

This issue happens only when `closeOnInsideClick={true}`.

**Comment by mlaursen** [comment]
Sorry, I was on vacation! But this looks good to me. I'll look into releasing the patch later today (I just need to remember what I have set up for this project for releases.. been awhile :) )

**Comment by mlaursen** [comment]
@williamboman  It should be published now. Let me know if I messed up the publication for this one since it's been a bit..

**Comment by williamboman** [comment]
> @williamboman It should be published now. Let me know if I messed up the publication for this one since it's been a bit..

Awesome, thanks a lot! Will try it out asap.

**Pull request merged**
